define(["./XactionComponent.ext","../Logger","../lib/jquery","./BaseComponent","../dashboard/Utils"],function(e,t,a,o){var n=o.extend({reset:function(){this.timeplot=void 0,this.chartDefinition.dateRangeInput=this.InitialDateRangeInput,this.listeners=this.InitialListeners
},update:function(){var o=this,n=o.chartDefinition;if(o.InitialListeners=void 0==o.InitialListeners?o.listeners:o.InitialListeners,o.InitialDateRangeInput=void 0==o.InitialDateRangeInput?n.dateRangeInput:o.InitialDateRangeInput,1==n.updateOnDateRangeInputChange||void 0==o.timeplot||void 0==n.dateRangeInput){void 0!=n.dateRangeInput&&void 0==o.timeplot&&(n.dateRangeInput=o.dashboard.getComponent(n.dateRangeInput),o.startDateParameter=n.dateRangeInput.parameter[0],o.endDateParameter=n.dateRangeInput.parameter[1],o.listeners=void 0==o.listeners?[]:o.listeners,o.listeners=o.listeners.concat(o.startDateParameter).concat(o.endDateParameter)),"undefined"!=typeof Timeplot&&void 0==o.dashboard.timePlotColors&&(o.dashboard.timePlotColors=[new Timeplot.Color("#820000"),new Timeplot.Color("#13E512"),new Timeplot.Color("#1010E1"),new Timeplot.Color("#E532D1"),new Timeplot.Color("#1D2DE1"),new Timeplot.Color("#83FC24"),new Timeplot.Color("#A1D2FF"),new Timeplot.Color("#73F321")]);
var i=new Timeplot.DefaultTimeGeometry({gridColor:"#000000",axisLabelsPlacement:"top",gridType:"short",yAxisColor:"rgba(255,255,255,0)",gridColor:"rgba(100,100,100,1)"}),r=new Timeplot.DefaultValueGeometry({gridColor:"#000000",min:0,axisLabelsPlacement:"left",gridType:"short",valueFormat:function(e){return toFormatedString(e)
}}),l=new Timeplot.DefaultEventSource,s=new Timeplot.DefaultEventSource;if(void 0==n)return t.log("Fatal - No chart definition passed","error"),void 0;
void 0==n.showValues&&(n.showValues=!0);var d="function"==typeof n.columns?n.columns():n.columns;
if(void 0==d||0==d.length)return t.log("Fatal - No 'columns' property passed in chartDefinition","error"),void 0;
var p=a("<div></div>");void 0!=n.title&&p.append('<span style="text-transform: lowercase;">'+n.title+"&nbsp; &nbsp; &nbsp;</span>");
for(var m=[],u=0,h=0;u<d.length;u++,h++){h=h>7?0:h,p.append('<span id="'+o.name+"Plot"+u+'Header" style="color:'+o.dashboard.timePlotColors[h].toHexString()+'">'+d[u]+" &nbsp;&nbsp;</span>");
var g={id:o.name+"Plot"+u,name:d[u],dataSource:new Timeplot.ColumnSource(l,u+1),valueGeometry:r,timeGeometry:i,lineColor:o.dashboard.timePlotColors[h],showValues:n.showValues,hideZeroToolTipValues:void 0!=n.hideZeroToolTipValues?n.hideZeroToolTipValues:!1,showValuesMode:void 0!=n.showValuesMode?n.showValuesMode:"header",toolTipFormat:function(e,t){return t._name+" = "+toFormatedString(e)
},headerFormat:function(e,t){return t._name+" = "+toFormatedString(e)+"&nbsp;&nbsp;"
}};1==n.dots&&(g.dotColor=o.dashboard.timePlotColors[h]),1==n.fill&&(g.fillColor=o.dashboard.timePlotColors[h].transparency(.5)),m.push(new Timeplot.createPlotInfo(g))
}var s=void 0,v=void 0;(void 0!=n.dateRangeInput||n.events&&1==n.events.show)&&(o.rangeColor="00FF00",s=new Timeplot.DefaultEventSource,v=Timeplot.createPlotInfo({id:void 0!=n.dateRangeInput?"eventPlot":"events",eventSource:s,timeGeometry:i,lineColor:"#FF0000",rangeColor:o.rangeColor,getSelectedRegion:function(e,t){o.updateDateRangeInput(e,t)
}}),m.push(v)),a("#"+o.htmlObject).html(p),a("#"+o.htmlObject).append("<div class='timeplot'></div>"),n.height>0&&a("#"+o.htmlObject+" > div.timeplot").css("height",n.height),n.width>0&&a("#"+o.htmlObject+" > div.timeplot").css("width",n.width),timeplot=Timeplot.create(a("#"+o.htmlObject+" > div.timeplot")[0],m),o.timeplot=timeplot,o.geometry=i;
var c=e.getCdfXaction("pentaho-cdf/actions","timelinefeeder.xaction",null,n);if(n.events&&1==n.events.show){var f=e.getCdfXaction("pentaho-cdf/actions","timelineeventfeeder.xaction",null,n.events);
timeplot.loadText(c,",",l,null,null,function(e){timeplot.loadJSON(f,s,function(t){if(t.events=o.filterEvents(t.events,e),n.dateRangeInput){var a=timeplot._plots[timeplot._plots.length-1];
"eventPlot"==a._id&&a._addSelectEvent(o.dashboard.getParameterValue(o.startDateParameter)+" 00:00:00",o.dashboard.getParameterValue(o.endDateParameter)+" 23:59:59",s,"iso8601",i._earliestDate,i._latestDate)
}})})}else timeplot.loadText(c,",",l,null,null,function(){if(n.dateRangeInput){var e=timeplot._plots[timeplot._plots.length-1];
"eventPlot"==e._id&&e._addSelectEvent(o.dashboard.getParameterValue(o.startDateParameter)+" 00:00:00",o.dashboard.getParameterValue(o.endDateParameter)+" 23:59:59",s,"iso8601",i._earliestDate,i._latestDate)
}})}else if(0!=o.updateTimeplot&&o.timeplot._plots.length>0){var D=o.timeplot._plots[o.timeplot._plots.length-1];
"eventPlot"==D._id&&D._addSelectEvent(o.dashboard.getParameterValue(o.startDateParameter)+" 00:00:00",o.dashboard.getParameterValue(o.endDateParameter)+" 23:59:59",D._eventSource,"iso8601",o.geometry._earliestDate,o.geometry._latestDate)
}},filterEvents:function(e,t){var a=[],o=MetaLayer.toDateString(new Date(t.earliestDate)),n=MetaLayer.toDateString(new Date(t.latestDate));
for(i=0;i<e.length;i++)e[i].start>=o&&(void 0==e[i].end&&e[i].start<=n||e[i].end<=n)&&a.push(e[i]);
return a},updateDateRangeInput:function(e,t){var a=function(e){var t="0"+(e.getMonth()+1),a="0"+e.getDate();
return e.getFullYear()+"-"+t.substring(t.length-2,t.length)+"-"+a.substring(a.length-2,a.length)
};if(void 0!=this.chartDefinition.dateRangeInput){if(e>t){var o=e;e=t,t=o}this.dashboard.setParameter(this.startDateParameter,a(e)),this.dashboard.setParameter(this.endDateParameter,a(t)),this.updateTimeplot=!1,this.dashboard.update(this.chartDefinition.dateRangeInput),this.dashboard.fireChange(this.startDateParameter,a(e)),this.updateTimeplot=!0
}}});return n});